MarkomApplication/_01.MarkomApplication.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _02.MarkomApplication.ModelAccess;
using _03.MarkomApplication.ModelView;
using _04.MarkomApplication.ModelData;

namespace _01.MarkomApplication.Web.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string searchName, string searchCode, string searchDescription, DateTime? searchDate, string searchCreatedProduct)
        {
            List<ProductModelView> List = new List<ProductModelView>();
            List = ProductModelAccess.GetListAll(searchName, searchCode, searchDescription, searchDate, searchCreatedProduct);
            ViewBag.DataKosong = ProductModelAccess.DataKosong;
            return PartialView("List", List);
        }

        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(ProductModelView paramModel)
        {
            try
            {
                ProductModelAccess.Message = string.Empty;

                //Create auto generate product_code
                using (var db = new Db_MarkomEntities())
                {
                    string nol = "";
                    m_product cek = db.m_product.OrderByDescending(x => x.code).First();
                    int simpan = int.Parse(cek.code.Substring(3));
                    simpan++;
                    for (int i = simpan.ToString().Length; i < 4; i++)
                    {
                        nol = nol + "0";
                    }
                    paramModel.code = "PR" + nol + simpan;
                }

                paramModel.createdBy = "Administrator";
                paramModel.createdDate = DateTime.Now;
                paramModel.isDelete = false;

                if (null == paramModel.name)
                {
                    ProductModelAccess.Message = "Anda belum memasukan semua data. Silahkan ulangi kembali";
                }
                if (string.IsNullOrEmpty(ProductModelAccess.Message))
                {
                    return Json(new
                    {
                        success = ProductModelAccess.Insert(paramModel),
                        message = paramModel.code
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = ProductModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(Int32 paramId)
        {
            return PartialView(ProductModelAccess.GetDetailById(paramId));
        }

        [HttpPost]
        public ActionResult Edit(ProductModelView paramModel)
        {
            try
            {
                ProductModelAccess.Message = string.Empty;

                paramModel.updatedBy = "Zoni";
                paramModel.updatedDate = DateTime.Now;

                if (null == paramModel.name)
                {
                    ProductModelAccess.Message = "Anda belum memasukan semua data. Silahkan ulangi kembali";
                }
                if (string.IsNullOrEmpty(ProductModelAccess.Message))
                {
                    return Json(new
                    {
                        success = ProductModelAccess.Update(paramModel),
                        message = ProductModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = ProductModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Detail(Int32 paramId)
        {
            return PartialView(ProductModelAccess.GetDetailById(paramId));
        }

        public ActionResult Delete(Int32 paramId)
        {
            return PartialView(ProductModelAccess.GetDetailById(paramId));
        }

        [HttpPost]
        public ActionResult Delete(ProductModelView paramModel)
        {
            try
            {
                return Json(new
                {
                    success = ProductModelAccess.Delete(paramModel),
                    message = ProductModelAccess.Message
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }









    }
}

MarkomApplication/_01.MarkomApplication.Web/Views/Product/Create.cshtml
@model _03.MarkomApplication.ModelView.ProductModelView

@{
    ViewBag.Title = "Create";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <label>*Product Code</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>*Product Name</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Unit Name" } })
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>Description</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Description" } })
            </div>
        </div>
        <div class="row" style="padding-top:35px">
            <div class="col-md-12">
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-block btn-primary" id="add_product_save" style="width:80px; float:right; margin-top:0%; margin-right:5px">Save</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Product/Delete.cshtml
@model _03.MarkomApplication.ModelView.ProductModelView

@{
    ViewBag.Title = "Delete";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row" style="padding-top:5px">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.id)
                @Html.HiddenFor(model => model.code)
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-block btn-primary" id="delete_product_save" style="width:80px; float:left; margin-top:0%">Delete</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Product/Detail.cshtml
@model _03.MarkomApplication.ModelView.ProductModelView

@{
    ViewBag.Title = "Detail";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <label>*Product Code</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>*Product Name</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Type Unit Name" } })
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>Description</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Type Description" } })
            </div>
        </div>
        <div class="row" style="padding-top:35px">
            <div class="col-md-12">
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Product/Edit.cshtml
@model _03.MarkomApplication.ModelView.ProductModelView

@{
    ViewBag.Title = "Edit";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <label>*Product Code</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>*Product Name</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Unit Name" } })
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>Description</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Description" } })
            </div>
        </div>
        <div class="row" style="padding-top:35px">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.id)
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-block btn-primary" id="edit_product_save" style="width:80px; float:right; margin-top:0%; margin-right:5px">Update</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">List Product</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="row" style="padding-bottom:10px">
                            <div class="col-md-9">
                                <div class="alert col-md-8" style="background-color:#cdeaff; color:#007bff; font-weight:bold; margin-bottom:0%; max-width:100%">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <button type="button" class="btn btn-block btn-primary" id="add_product" style="width:100px; float:right">Add</button>
                            </div>
                        </div>
                        <div id="table-list-product"></div> <!-- Tempat List -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- modal popup bootstrap - CRUD Form -->
<div class="modal fade" id="modal-form-product">
    <div class="modal-dialog" role="document" style="width:500px; max-width:100%">
        <!-- modal content -->
        <div class="modal-content" style=" border-color:#007bff">
            <!-- modal header -->
            <div class="modal-header" id="modal-header" style="background-color:#007bff; color:white; font-size:larger">
            </div>
            <!-- modal body dan footer -->
            <div class="div-bind-form" id="div-bind-form" style="margin-top: 5px; margin-left: 20px; margin-right: 20px; margin-bottom: 15px">
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
</div>


<!-- modal popup delete -->
<div class="modal fade" id="modal-form-product-delete">
    <div class="modal-dialog" role="document" style="width:230px; max-width:100%">
        <div class="modal-content" style=" border-color:gainsboro">
            <div class="modal-header" style="background-color:gainsboro">
                <div class="modal-title" id="modal-header-delete" style="margin:auto; font-size:large">
                    Judul Modal
                </div>
            </div>
            <div class="div-bind-form" id="div-bind-form" style=" margin-left: 5px; margin-right: 5px; margin-bottom: 5px">
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts{
    <script type="text/javascript">
        var vjs_loading = '<div class="progress progress-striped active" style="margin-bottom:0"> <div class="progress-bar" style="width:100%"> </div> </div>';

        $(document).ready(function () {
            ShowList();
            $(".alert").hide();
        });

        //Variable seacrh
        var vjs_search_productname = '';
        var vjs_search_productcode = '';
        var vjs_search_description = '';
        let vjs_search_date = '';
        var vjs_search_createdproduct = '';

        function ShowList() {
            $.ajax({
                url: '@Url.Action("List", "Product")',
                type: 'get',
                data: {
                    SearchName: vjs_search_productname,
                    searchCode: vjs_search_productcode,
                    searchDescription: vjs_search_description,
                    searchDate: vjs_search_date,
                    searchCreatedProduct: vjs_search_createdproduct
                },
                success: function (result) {
                    $("#table-list-product").html(result);
                }
            });
        };

        //Search data Product
        $(document).on("click", "#search_product", function () {
            vjs_search_productname = $("#search_productname").val();
            vjs_search_productcode = $("#search_productcode").val();
            vjs_search_description = $("#search_description").val();
            vjs_search_date = $("#search_date").val();
            vjs_search_createdproduct = $("#search_created_by").val();
            ShowList();
        });


        //Popup Tambah Product
        $(document).on("click", "#add_product", function () {
            $("#modal-form-product").modal("show");
            $("#modal-header").html("Add Product");
            $.ajax({
                url: '@Url.Action("Create", "Product")',
                type: 'get',
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Save Add data Product
        $(document).on("click", "#add_product_save", function () {
            var vjs_name = $("#name").val();
            vjs_name == "" ? $(".validasi2").show() : $(".validasi2").hide();
            var vjs_description = $("#description").val();

            var item = {
                name: vjs_name,
                description: vjs_description
            };
            $.ajax({
                url: '@Url.Action("Create", "Product")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-product").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Saved! New role has been add with code " + result.message + " !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });


        //Popup edit Product
        $(document).on("click", "#edit_product", function () {
            var vjs_id = $(this).attr("data-id");
            var vjs_name_popup = $(this).attr("data-name");
            var vjs_code_popup = $(this).attr("data-code");
            $("#modal-form-product").modal("show");
            $("#modal-header").html("Edit Product - "+vjs_name_popup+" ("+vjs_code_popup+")");

            $.ajax({
                url: '@Url.Action("Edit", "Product")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Save Edit data Product
        $(document).on("click", "#edit_product_save", function () {
            var vjs_id = $("#id").val();
            var vjs_name = $("#name").val();
            vjs_name == "" ? $(".validasi2").show() : $(".validasi2").hide();
            var vjs_description = $("#description").val();

            var item = {
                id: vjs_id,
                name: vjs_name,
                description: vjs_description
            };
            $.ajax({
                url: '@Url.Action("Edit", "Product")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-product").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Updated! Data product has been updated !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });


        //Popup detail/view Product
        $(document).on("click", "#detail_product", function () {
            var vjs_id = $(this).attr("data-id");
            var vjs_name_popup = $(this).attr("data-name");
            var vjs_code_popup = $(this).attr("data-code");
            $("#modal-form-product").modal("show");
            $("#modal-header").html("View Product - "+vjs_name_popup+" ("+vjs_code_popup+")");

            $.ajax({
                url: '@Url.Action("Detail", "Product")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Popup delete Product
        $(document).on("click", "#delete_product", function () {
            var vjs_id = $(this).attr("data-id");
            $("#modal-form-product-delete").modal("show");
            $("#modal-header-delete").html("Delete Data ?");

            $.ajax({
                url: '@Url.Action("Delete", "Product")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                }
            });
        });

        //Save delete data Product
        $(document).on("click", "#delete_product_save", function () {
            var vjs_id = $("#id").val();
            var vjs_code = $("#code").val();
            var item = {
                id: vjs_id,
                code: vjs_code
            };
            $.ajax({
                url: '@Url.Action("Delete", "Product")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-product-delete").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Deleted! Data product with code "+vjs_code+" has been deleted !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });





    </script>
}

MarkomApplication/_01.MarkomApplication.Web/Views/Product/List.cshtml
@model IEnumerable<_03.MarkomApplication.ModelView.ProductModelView>

@{
    ViewBag.Title = "List";
    int no = 1;
}

<div class="row" style="width:100%; margin-left:0%; padding-bottom:10px">
    <input class="form-control col-xl-2" id="search_productcode" placeholder="Product Code" style="margin:auto" />
    <input class="form-control col-xl-2" id="search_productname" placeholder="Product Name" style="margin:auto" />
    <input class="form-control col-xl-2" id="search_description" placeholder="Description" style="margin:auto" />
    <input class="form-control col-xl-2" id="search_date" placeholder="Created" onfocus="this.type='date'" style="margin:auto" />
    <input class="form-control col-xl-2" id="search_created_by" placeholder="Created By" style="margin:auto" />
    <button type="button" class="btn btn-block bg-gradient-warning" style="width:100px; float:right" id="search_product">Search</button>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>No</th>
            <th>Product Code</th>
            <th>Product Name</th>
            <th>Description</th>
            <th>Created Date</th>
            <th>Created By</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @no
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tanggal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.createdBy)
                </td>
                <td>
                    <a href="#" id="detail_product" data-code="@item.code" data-name="@item.name" data-id="@item.id"><span class="fas fa-search"></span></a>
                    <a href="#" id="edit_product" data-code="@item.code" data-name="@item.name" data-id="@item.id"><span class="fas fa-edit"></span></a>
                    <a href="#" id="delete_product" data-id="@item.id"><span class="fas fa-trash"></span></a>
                </td>
            </tr>
            no++;
        }
    </tbody>
</table>
<div style="text-align: center; font-size: large; color: #007bff">@ViewBag.DataKosong</div>