MarkomApplication/_01.MarkomApplication.Web/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _02.MarkomApplication.ModelAccess;
using _03.MarkomApplication.ModelView;
using _04.MarkomApplication.ModelData;

namespace _01.MarkomApplication.Web.Controllers
{
    public class UnitController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string searchName, string searchCode, DateTime? searchDate, string searchCreatedUnit)
        {
            List<UnitModelView> List = new List<UnitModelView>();
            List = UnitModelAccess.GetListAll(searchName, searchCode, searchDate, searchCreatedUnit);
            ViewBag.UnitCode = new SelectList(List, "code", "code");
            ViewBag.UnitName = new SelectList(List, "name", "name");
            ViewBag.DataKosong = UnitModelAccess.DataKosong;
            return PartialView("List", List);
        }

        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(UnitModelView paramModel)
        {
            try
            {
                UnitModelAccess.Message = string.Empty;

                //Create auto generate unit_code
                using (var db = new Db_MarkomEntities())
                {
                    string nol = "";
                    m_unit cek = db.m_unit.OrderByDescending(x => x.code).First();
                    int simpan = int.Parse(cek.code.Substring(3));
                    simpan++;
                    for (int i = simpan.ToString().Length; i < 4; i++)
                    {
                        nol = nol + "0";
                    }
                    paramModel.code = "UN" + nol + simpan;
                }

                paramModel.createdBy = "Administrator";
                paramModel.createdDate = DateTime.Now;
                paramModel.isDelete = false;

                if (null == paramModel.name)
                {
                    UnitModelAccess.Message = "Anda belum memasukan semua data. Silahkan ulangi kembali";
                }
                if (string.IsNullOrEmpty(UnitModelAccess.Message))
                {
                    return Json(new
                    {
                        success = UnitModelAccess.Insert(paramModel),
                        message = paramModel.code
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = UnitModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(Int32 paramId)
        {
            return PartialView(UnitModelAccess.GetDetailById(paramId));
        }

        [HttpPost]
        public ActionResult Edit(UnitModelView paramModel)
        {
            try
            {
                UnitModelAccess.Message = string.Empty;

                paramModel.updatedBy = "Zoni";
                paramModel.updatedDate = DateTime.Now;

                if (null == paramModel.name)
                {
                    UnitModelAccess.Message = "Anda belum memasukan semua data. Silahkan ulangi kembali";
                }
                if (string.IsNullOrEmpty(UnitModelAccess.Message))
                {
                    return Json(new
                    {
                        success = UnitModelAccess.Update(paramModel),
                        message = UnitModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = UnitModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Detail(Int32 paramId)
        {
            return PartialView(UnitModelAccess.GetDetailById(paramId));
        }

        public ActionResult Delete(Int32 paramId)
        {
            return PartialView(UnitModelAccess.GetDetailById(paramId));
        }

        [HttpPost]
        public ActionResult Delete(UnitModelView paramModel)
        {
            try
            {
                return Json(new
                {
                    success = UnitModelAccess.Delete(paramModel),
                    message = UnitModelAccess.Message
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }





    }
}

MarkomApplication/_01.MarkomApplication.Web/Views/Unit/Create.cshtml
@model _03.MarkomApplication.ModelView.UnitModelView

@{
    ViewBag.Title = "Create";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <label>*Unit Code</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>*Unit Name</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Unit Name" } })
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>Description</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Description" } })
            </div>
        </div>
        <div class="row" style="padding-top:35px">
            <div class="col-md-12">
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-block btn-primary" id="add_unit_save" style="width:80px; float:right; margin-top:0%; margin-right:5px">Save</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Unit/Delete.cshtml
@model _03.MarkomApplication.ModelView.UnitModelView

@{
    ViewBag.Title = "Delete";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row" style="padding-top:5px">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.id)
                @Html.HiddenFor(model => model.code)
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-block btn-primary" id="delete_unit_save" style="width:80px; float:left; margin-top:0%">Delete</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Unit/Detail.cshtml
@model _03.MarkomApplication.ModelView.UnitModelView

@{
    ViewBag.Title = "Detail";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <label>*Unit Code</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>*Unit Name</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Type Unit Name" } })
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>Description</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Type Description" } })
            </div>
        </div>
        <div class="row" style="padding-top:35px">
            <div class="col-md-12">
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Unit/Edit.cshtml
@model _03.MarkomApplication.ModelView.UnitModelView

@{
    ViewBag.Title = "Edit";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <label>*Unit Code</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>*Unit Name</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Unit Name" } })
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-4">
                <label>Description</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Description" } })
            </div>
        </div>
        <div class="row" style="padding-top:35px">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.id)
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-block btn-primary" id="edit_unit_save" style="width:80px; float:right; margin-top:0%; margin-right:5px">Update</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Unit/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">List Unit</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="row" style="padding-bottom:10px">
                            <div class="col-md-9">
                                <div class="alert col-md-8" style="background-color:#cdeaff; color:#007bff; font-weight:bold; margin-bottom:0%; max-width:100%">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <button type="button" class="btn btn-block btn-primary" id="add_unit" style="width:100px; float:right">Add</button>
                            </div>
                        </div>
                        <div id="table-list-unit"></div> <!-- Tempat List -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- modal popup bootstrap - CRUD Form -->
<div class="modal fade" id="modal-form-unit">
    <div class="modal-dialog" role="document" style="width:400px; max-width:100%">
        <!-- modal content -->
        <div class="modal-content" style=" border-color:#007bff">
            <!-- modal header -->
            <div class="modal-header" id="modal-header" style="background-color:#007bff; color:white; font-size:larger">
            </div>
            <!-- modal body dan footer -->
            <div class="div-bind-form" id="div-bind-form" style="margin-top: 5px; margin-left: 20px; margin-right: 20px; margin-bottom: 15px">
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
</div>


<!-- modal popup delete -->
<div class="modal fade" id="modal-form-unit-delete">
    <div class="modal-dialog" role="document" style="width:230px; max-width:100%">
        <div class="modal-content" style=" border-color:gainsboro">
            <div class="modal-header" style="background-color:gainsboro">
                <div class="modal-title" id="modal-header-delete" style="margin:auto; font-size:large">
                    Judul Modal
                </div>
            </div>
            <div class="div-bind-form" id="div-bind-form" style=" margin-left: 5px; margin-right: 5px; margin-bottom: 5px">
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts{
    <script type="text/javascript">
        var vjs_loading = '<div class="progress progress-striped active" style="margin-bottom:0"> <div class="progress-bar" style="width:100%"> </div> </div>';

        $(document).ready(function () {
            ShowList();
            $(".alert").hide();
        });

        //Variable search
        var vjs_search_unitname = '';
        var vjs_search_unitcode = '';
        let vjs_search_date = '';
        var vjs_search_createdunit = '';

        function ShowList() {
            $.ajax({
                url: '@Url.Action("List", "Unit")',
                type: 'get',
                data: {
                    SearchName: vjs_search_unitname,
                    searchCode: vjs_search_unitcode,
                    searchDate: vjs_search_date,
                    searchCreatedUnit: vjs_search_createdunit
                },
                success: function (result) {
                    $("#table-list-unit").html(result);
                }
            });
        };

        //Search data unit
        $(document).on("click", "#search_unit", function () {
            vjs_search_unitname = $("#search_unitname").val();
            vjs_search_unitcode = $("#search_unitcode").val();
            vjs_search_date = $("#search_date").val();
            vjs_search_createdunit = $("#search_created_by").val();
            ShowList();
        });


        //Popup Tambah Unit
        $(document).on("click", "#add_unit", function () {
            $("#modal-form-unit").modal("show");
            $("#modal-header").html("Add Unit");
            $.ajax({
                url: '@Url.Action("Create", "Unit")',
                type: 'get',
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Save Add data Unit
        $(document).on("click", "#add_unit_save", function () {
            var vjs_name = $("#name").val();
            vjs_name == "" ? $(".validasi2").show() : $(".validasi2").hide();
            var vjs_description = $("#description").val();

            var item = {
                name: vjs_name,
                description: vjs_description
            };
            $.ajax({
                url: '@Url.Action("Create", "Unit")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-unit").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Saved! New role has been add with code " + result.message + " !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });


        //Popup edit Unit
        $(document).on("click", "#edit_unit", function () {
            var vjs_id = $(this).attr("data-id");
            var vjs_name_popup = $(this).attr("data-name");
            var vjs_code_popup = $(this).attr("data-code");
            $("#modal-form-unit").modal("show");
            $("#modal-header").html("Edit Unit - "+vjs_name_popup+" ("+vjs_code_popup+")");

            $.ajax({
                url: '@Url.Action("Edit", "Unit")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Save Edit data Unit
        $(document).on("click", "#edit_unit_save", function () {
            var vjs_id = $("#id").val();
            var vjs_name = $("#name").val();
            vjs_name == "" ? $(".validasi2").show() : $(".validasi2").hide();
            var vjs_description = $("#description").val();

            var item = {
                id: vjs_id,
                name: vjs_name,
                description: vjs_description
            };
            $.ajax({
                url: '@Url.Action("Edit", "Unit")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-unit").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Updated! Data unit has been updated !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });


        //Popup detail/view Unit
        $(document).on("click", "#detail_unit", function () {
            var vjs_id = $(this).attr("data-id");
            var vjs_name_popup = $(this).attr("data-name");
            var vjs_code_popup = $(this).attr("data-code");
            $("#modal-form-unit").modal("show");
            $("#modal-header").html("View Unit - "+vjs_name_popup+" ("+vjs_code_popup+")");

            $.ajax({
                url: '@Url.Action("Detail", "Unit")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Popup delete Unit
        $(document).on("click", "#delete_unit", function () {
            var vjs_id = $(this).attr("data-id");
            $("#modal-form-unit-delete").modal("show");
            $("#modal-header-delete").html("Delete Data ?");

            $.ajax({
                url: '@Url.Action("Delete", "Unit")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                }
            });
        });

        //Save delete data Unit
        $(document).on("click", "#delete_unit_save", function () {
            var vjs_id = $("#id").val();
            var vjs_code = $("#code").val();
            var item = {
                id: vjs_id,
                code: vjs_code
            };
            $.ajax({
                url: '@Url.Action("Delete", "Unit")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-unit-delete").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Deleted! Data unit with code "+vjs_code+" has been deleted !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });





    </script>
}

MarkomApplication/_01.MarkomApplication.Web/Views/Unit/List.cshtml
@model IEnumerable<_03.MarkomApplication.ModelView.UnitModelView>

@{
    ViewBag.Title = "List";
    int no = 1;
}
<div class="row" style="width:100%; margin-left:0%; padding-bottom:10px">
    <select id="search_unitcode" class="form-control col-xl-3" style="margin:auto">
        <option value="" disabled selected hidden>-Select Unit Code-</option>
        @foreach (var item in ViewBag.UnitCode)
        {
            <option value="@item.Value">@item.Value</option>
        }
    </select>
    <select id="search_unitname" class="form-control col-xl-3" style="margin:auto">
        <option value="" disabled selected hidden>-Select Unit Name-</option>
        @foreach (var item in ViewBag.UnitName)
        {
            <option value="@item.Value">@item.Value</option>
        }
    </select>
    <input class="form-control col-xl-2" id="search_date" placeholder="Created" onfocus="this.type='date'" style="margin:auto" />
    <input class="form-control col-xl-2" id="search_created_by" placeholder="Created By" style="margin:auto" />
    <button type="button" class="btn btn-block bg-gradient-warning" style="width:100px; float:right" id="search_unit">Search</button>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>No</th>
            <th>Unit Code</th>
            <th>Unit Name</th>
            <th>Created Date</th>
            <th>Created By</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @no
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tanggal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.createdBy)
                </td>
                <td>
                    <a href="#" id="detail_unit" data-code="@item.code" data-name="@item.name" data-id="@item.id"><span class="fas fa-search"></span></a>
                    <a href="#" id="edit_unit" data-code="@item.code" data-name="@item.name" data-id="@item.id"><span class="fas fa-edit"></span></a>
                    @if (item.deleteUnit == "")
                    {
                        <a href="#" id="delete_unit" data-id="@item.id"><span class="fas fa-trash"></span></a>
                    }
                </td>
            </tr>
            no++;
        }
    </tbody>
</table>
<div style="text-align: center; font-size: large; color: #007bff">@ViewBag.DataKosong</div>