MarkomApplication/_01.MarkomApplication.Web/Controllers/SouvenirController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _02.MarkomApplication.ModelAccess;
using _03.MarkomApplication.ModelView;
using _04.MarkomApplication.ModelData;

namespace _01.MarkomApplication.Web.Controllers
{
    public class SouvenirController : Controller
    {
        // GET: Souvenir
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string searchName, string searchCode, Int32 searchUnitName, DateTime? searchDate, string searchCreatedSouvenir)
        {
            List<SouvenirModelView> List = new List<SouvenirModelView>();
            List = SouvenirModelAccess.GetListAll(searchName, searchCode, searchUnitName, searchDate, searchCreatedSouvenir);
            ViewBag.UnitName = new SelectList(List, "mUnitId", "nameUnit");
            ViewBag.DataKosong = SouvenirModelAccess.DataKosong;
            return PartialView("List", List);
        }

        public ActionResult Create()
        {
            ViewBag.UnitName = new SelectList(SouvenirModelAccess.UnitName(), "id", "name");
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(SouvenirModelView paramModel)
        {
            try
            {
                SouvenirModelAccess.Message = string.Empty;

                //Create auto generate souvenir_code
                using (var db = new Db_MarkomEntities())
                {
                    string nol = "";
                    m_souvenir cek = db.m_souvenir.OrderByDescending(x => x.code).First();
                    int simpan = int.Parse(cek.code.Substring(3));
                    simpan++;
                    for (int i = simpan.ToString().Length; i < 4; i++)
                    {
                        nol = nol + "0";
                    }
                    paramModel.code = "SV" + nol + simpan;
                }

                paramModel.createdBy = "Administrator";
                paramModel.createdDate = DateTime.Now;
                paramModel.isDelete = false;

                if (null == paramModel.name || "0" == (paramModel.mUnitId).ToString())
                {
                    SouvenirModelAccess.Message = "Anda belum memasukan semua data. Silahkan ulangi kembali";
                }
                if (string.IsNullOrEmpty(SouvenirModelAccess.Message))
                {
                    return Json(new
                    {
                        success = SouvenirModelAccess.Insert(paramModel),
                        message = paramModel.code
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = SouvenirModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(Int32 paramId)
        {
            ViewBag.UnitName = new SelectList(SouvenirModelAccess.UnitName(), "id", "name");
            return PartialView(SouvenirModelAccess.GetDetailById(paramId));
        }

        [HttpPost]
        public ActionResult Edit(SouvenirModelView paramModel)
        {
            try
            {
                SouvenirModelAccess.Message = string.Empty;

                paramModel.updatedBy = "Zoni";
                paramModel.updatedDate = DateTime.Now;

                if (null == paramModel.name || "0" == (paramModel.mUnitId).ToString())
                {
                    SouvenirModelAccess.Message = "Anda belum memasukan semua data. Silahkan ulangi kembali";
                }
                if (string.IsNullOrEmpty(SouvenirModelAccess.Message))
                {
                    return Json(new
                    {
                        success = SouvenirModelAccess.Update(paramModel),
                        message = SouvenirModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = SouvenirModelAccess.Message },
                    JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Detail(Int32 paramId)
        {
            ViewBag.UnitName = new SelectList(SouvenirModelAccess.UnitName(), "id", "name");
            return PartialView(SouvenirModelAccess.GetDetailById(paramId));
        }

        public ActionResult Delete(Int32 paramId)
        {
            return PartialView(SouvenirModelAccess.GetDetailById(paramId));
        }

        [HttpPost]
        public ActionResult Delete(SouvenirModelView paramModel)
        {
            try
            {
                return Json(new
                {
                    success = SouvenirModelAccess.Delete(paramModel),
                    message = SouvenirModelAccess.Message
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception hasError)
            {
                return Json(new { success = false, message = hasError.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }









    }
}

MarkomApplication/_01.MarkomApplication.Web/Views/Souvenir/Create.cshtml
@model _03.MarkomApplication.ModelView.SouvenirModelView

@{
    ViewBag.Title = "Create";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-2">
                <label>*Souvenir Code</label>
            </div>
            <div class="col-md-4">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
            <div class="col-md-2">
                <label style="float:right">*Unit Name</label>
            </div>
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.mUnitId, (IEnumerable<SelectListItem>)ViewBag.UnitName, "-Select Unit Name-", new { @class = "form-control" })
                @*@Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Unit Name" } })*@
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-2">
                <label>*Souvenir Name</label>
            </div>
            <div class="col-md-4">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Souvenir Name" } })
                <span class="validasiAlert validasi3" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
            <div class="col-md-2">
                <label style="float:right">Description</label>
            </div>
            <div class="col-md-4">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Description" } })
            </div>
        </div>
        <div class="row" style="padding-top:35px">
            <div class="col-md-12">
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-block btn-primary" id="add_souvenir_save" style="width:80px; float:right; margin-top:0%; margin-right:5px">Save</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Souvenir/Delete.cshtml
@model _03.MarkomApplication.ModelView.SouvenirModelView

@{
    ViewBag.Title = "Delete";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row" style="padding-top:5px">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.id)
                @Html.HiddenFor(model => model.code)
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-block btn-primary" id="delete_souvenir_save" style="width:80px; float:left; margin-top:0%">Delete</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Souvenir/Detail.cshtml
@model _03.MarkomApplication.ModelView.SouvenirModelView

@{
    ViewBag.Title = "Detail";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-2">
                <label>*Souvenir Code</label>
            </div>
            <div class="col-md-4">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
            <div class="col-md-2">
                <label style="float:right">*Unit Name</label>
            </div>
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.mUnitId, (IEnumerable<SelectListItem>)ViewBag.UnitName, "-Select Unit Name-", new { @class = "form-control", disabled = "disabled" })
                @*@Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Unit Name" } })*@
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-2">
                <label>*Souvenir Name</label>
            </div>
            <div class="col-md-4">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Type Souvenir Name" } })
                <span class="validasiAlert validasi3" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
            <div class="col-md-2">
                <label style="float:right">Description</label>
            </div>
            <div class="col-md-4">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Type Description" } })
            </div>
        </div>
        <div class="row" style="padding-top:35px">
            <div class="col-md-12">
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Souvenir/Edit.cshtml
@model _03.MarkomApplication.ModelView.SouvenirModelView

@{
    ViewBag.Title = "Edit";
}

<form style="color:#343a40">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-2">
                <label>*Souvenir Code</label>
            </div>
            <div class="col-md-4">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", placeholder = "Auto Generated" } })
                <span class="validasiAlert validasi1" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
            <div class="col-md-2">
                <label style="float:right">*Unit Name</label>
            </div>
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.mUnitId, (IEnumerable<SelectListItem>)ViewBag.UnitName, "-Select Unit Name-", new { @class = "form-control" })
                @*@Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Unit Name" } })*@
                <span class="validasiAlert validasi2" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
        </div>
        <div class="row" style="padding-top:10px">
            <div class="col-md-2">
                <label>*Souvenir Name</label>
            </div>
            <div class="col-md-4">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Souvenir Name" } })
                <span class="validasiAlert validasi3" style="color:red;font-size:smaller">*Harus diisi !!</span>
            </div>
            <div class="col-md-2">
                <label style="float:right">Description</label>
            </div>
            <div class="col-md-4">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "Type Description" } })
            </div>
        </div>
        <div class="row" style="padding-top:35px">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.id)
                <button type="button" class="btn btn-block bg-gradient-warning" style="width:80px; float:right" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-block btn-primary" id="edit_souvenir_save" style="width:80px; float:right; margin-top:0%; margin-right:5px">Save</button>
            </div>
        </div>
    </div>
</form>

MarkomApplication/_01.MarkomApplication.Web/Views/Souvenir/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">List Souvenir</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="row" style="padding-bottom:10px">
                            <div class="col-md-9">
                                <div class="alert col-md-8" style="background-color:#cdeaff; color:#007bff; font-weight:bold; margin-bottom:0%; max-width:100%">
                                </div>
                            </div>
                            <div class="col-md-3">
                                <button type="button" class="btn btn-block btn-primary" id="add_souvenir" style="width:100px; float:right">Add</button>
                            </div>
                        </div>
                        <div id="table-list-souvenir"></div> <!-- Tempat List -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- modal popup bootstrap - CRUD Form -->
<div class="modal fade" id="modal-form-souvenir">
    <div class="modal-dialog" role="document" style="width:850px; max-width:100%">
        <!-- modal content -->
        <div class="modal-content" style=" border-color:#007bff">
            <!-- modal header -->
            <div class="modal-header" id="modal-header" style="background-color:#007bff; color:white; font-size:larger">
            </div>
            <!-- modal body dan footer -->
            <div class="div-bind-form" id="div-bind-form" style="margin-top: 5px; margin-left: 20px; margin-right: 20px; margin-bottom: 15px">
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
</div>


<!-- modal popup delete -->
<div class="modal fade" id="modal-form-souvenir-delete">
    <div class="modal-dialog" role="document" style="width:230px; max-width:100%">
        <div class="modal-content" style=" border-color:gainsboro">
            <div class="modal-header" style="background-color:gainsboro">
                <div class="modal-title" id="modal-header-delete" style="margin:auto; font-size:large">
                    Judul Modal
                </div>
            </div>
            <div class="div-bind-form" id="div-bind-form" style=" margin-left: 5px; margin-right: 5px; margin-bottom: 5px">
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script type="text/javascript">
        var vjs_loading = '<div class="progress progress-striped active" style="margin-bottom:0"> <div class="progress-bar" style="width:100%"> </div> </div>';
        $(document).ready(function () {
            ShowList();
            $(".alert").hide();
        });

        //Variable search
        var vjs_search_souvenirname = '';
        var vjs_search_souvenircode = '';
        var vjs_search_unitname=0;
        let vjs_search_date = '';
        var vjs_search_createdsouvenir = '';

        function ShowList() {
            $.ajax({
                url: '@Url.Action("List", "Souvenir")',
                type: 'get',
                data: {
                    SearchName: vjs_search_souvenirname,
                    searchCode: vjs_search_souvenircode,
                    searchUnitName: vjs_search_unitname,
                    searchDate: vjs_search_date,
                    searchCreatedSouvenir: vjs_search_createdsouvenir
                },
                success: function (result) {
                    $("#table-list-souvenir").html(result);
                }
            });
        };

        //Search data unit
        $(document).on("click", "#search_souvenir", function () {
            vjs_search_souvenirname = $("#search_souvenirname").val();
            vjs_search_souvenircode = $("#search_souvenircode").val();
            vjs_search_unitname = $("#search_unitname").val();
            vjs_search_date = $("#search_date").val();
            vjs_search_createdsouvenir = $("#search_created_by").val();
            ShowList();
        });


        //Popup Tambah Unit
        $(document).on("click", "#add_souvenir", function () {
            $("#modal-form-souvenir").modal("show");
            $("#modal-header").html("Add Souvenir");
            $.ajax({
                url: '@Url.Action("Create", "Souvenir")',
                type: 'get',
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Save Add data Unit
        $(document).on("click", "#add_souvenir_save", function () {
            var vjs_mUnitId = $("#mUnitId").val();
            vjs_mUnitId == "" ? $(".validasi2").show() : $(".validasi2").hide();
            var vjs_name = $("#name").val();
            vjs_name == "" ? $(".validasi3").show() : $(".validasi3").hide();
            var vjs_description = $("#description").val();

            var item = {
                mUnitId: vjs_mUnitId,
                name: vjs_name,
                description: vjs_description
            };
            $.ajax({
                url: '@Url.Action("Create", "Souvenir")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-souvenir").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Saved! New role has been add with code " + result.message + " !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });


        //Popup edit Souvenir
        $(document).on("click", "#edit_souvenir", function () {
            var vjs_id = $(this).attr("data-id");
            var vjs_name_popup = $(this).attr("data-name");
            var vjs_code_popup = $(this).attr("data-code");
            $("#modal-form-souvenir").modal("show");
            $("#modal-header").html("Edit Souvenir - "+vjs_name_popup+" ("+vjs_code_popup+")");

            $.ajax({
                url: '@Url.Action("Edit", "Souvenir")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Save Edit data Souvenir
        $(document).on("click", "#edit_souvenir_save", function () {
            var vjs_id = $("#id").val();
            var vjs_mUnitId = $("#mUnitId").val();
            vjs_mUnitId == "" ? $(".validasi2").show() : $(".validasi2").hide();
            var vjs_name = $("#name").val();
            vjs_name == "" ? $(".validasi3").show() : $(".validasi3").hide();
            var vjs_description = $("#description").val();

            var item = {
                id: vjs_id,
                mUnitId: vjs_mUnitId,
                name: vjs_name,
                description: vjs_description
            };
            $.ajax({
                url: '@Url.Action("Edit", "Souvenir")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-souvenir").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Updated! Data souvenir has been updated !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });


        //Popup detail/view Souvenir
        $(document).on("click", "#detail_souvenir", function () {
            var vjs_id = $(this).attr("data-id");
            var vjs_name_popup = $(this).attr("data-name");
            var vjs_code_popup = $(this).attr("data-code");
            $("#modal-form-souvenir").modal("show");
            $("#modal-header").html("View Souvenir - "+vjs_name_popup+" ("+vjs_code_popup+")");

            $.ajax({
                url: '@Url.Action("Detail", "Souvenir")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                    $(".validasiAlert").hide();
                }
            });
        });

        //Popup delete Souvenir
        $(document).on("click", "#delete_souvenir", function () {
            var vjs_id = $(this).attr("data-id");
            $("#modal-form-souvenir-delete").modal("show");
            $("#modal-header-delete").html("Delete Data ?");

            $.ajax({
                url: '@Url.Action("Delete", "Souvenir")',
                type: 'get',
                data: { paramId: vjs_id },
                success: function (result) {
                    $(".div-bind-form").html(result);
                }
            });
        });

        //Save delete data Souvenir
        $(document).on("click", "#delete_souvenir_save", function () {
            var vjs_id = $("#id").val();
            var vjs_code = $("#code").val();
            var item = {
                id: vjs_id,
                code: vjs_code
            };
            $.ajax({
                url: '@Url.Action("Delete", "Souvenir")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-form-souvenir-delete").modal("hide");
                        ShowList();
                        $(".alert").show().html("Data Deleted! Data unit with code "+vjs_code+" has been deleted !");
                        window.setTimeout(function () {
                            $(".alert").slideUp(500);
                        }, 3000);
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });





    </script>
}

MarkomApplication/_01.MarkomApplication.Web/Views/Souvenir/List.cshtml
@model IEnumerable<_03.MarkomApplication.ModelView.SouvenirModelView>

@{
    ViewBag.Title = "List";
    int no = 1;
}

<div class="row" style="width:100%; margin-left:0%; padding-bottom:10px">
    <input class="form-control col-xl-2" id="search_souvenircode" placeholder="Souvenir Code" style="margin:auto" />
    <input class="form-control col-xl-2" id="search_souvenirname" placeholder="Souvenir Name" style="margin:auto" />




    <select id="search_unitname" class="form-control col-xl-2" style="margin:auto">
        <option value=0 class="input-group" typeof="text"  selected >-Select Unit Name-</option>
        @foreach (var item in ViewBag.UnitName)
        {
            <option value=@item.Value>@item.Text</option>
        }
    </select>
    <input class="form-control col-xl-2" id="search_date" placeholder="Created" onfocus="this.type='date'" style="margin:auto" />
    <input class="form-control col-xl-2" id="search_created_by" placeholder="Created By" style="margin:auto" />
    <button type="button" class="btn btn-block bg-gradient-warning" style="width:100px; float:right" id="search_souvenir">Search</button>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>No</th>
            <th>Souvenir Code</th>
            <th>Souvenir Name</th>
            <th>Unit</th>
            <th>Created Date</th>
            <th>Created By</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @no
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nameUnit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tanggal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.createdBy)
                </td>
                <td>
                    <a href="#" id="detail_souvenir" data-code="@item.code" data-name="@item.name" data-id="@item.id"><span class="fas fa-search"></span></a>
                    <a href="#" id="edit_souvenir" data-code="@item.code" data-name="@item.name" data-id="@item.id"><span class="fas fa-edit"></span></a>
                    @if (item.deleteSouvenir == "")
                    {
                        <a href="#" id="delete_souvenir" data-id="@item.id"><span class="fas fa-trash"></span></a>
                    }
                </td>
            </tr>
            no++;
        }
    </tbody>
</table>
<div style="text-align: center; font-size: large; color: #007bff">@ViewBag.DataKosong</div>